version: "2"
services:
    django:
        image: devoff/web
        container_name: devoff_web
        command: "/bin/bash"
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/app
        working_dir: /usr/app/django
        stdin_open: true
        tty: true
        links:
            - postgres:postgres
            - redis:redis
        environment:
            PYTHONPATH: /usr/app/django/project
            DJANGO_SETTINGS_MODULE: app.config.settings.local
            SHELL: /bin/bash
        logging:
            driver: none
    # See:
    #   https://hub.docker.com/_/postgres/
    #   https://hub.docker.com/r/mdillon/postgis
    postgres:
        image: mdillon/postgis
        container_name: devoff_db
        restart: always
        volumes:
            - /usr/lib/postgresql
            - .:/usr/app/
        logging:
            driver: none

    redis:
        image: redis:latest
        container_name: devoff_redis
        restart: always
        ports:
            - "6379:6379"
